version: "3.8"

services:

  single-stage:
    image: kumargi/node-singlestage-app:latest
    container_name: single-stage
    ports:
      - "3002:3000"

  multi-stage:
    image: kumargi/node-multistage-app:latest
    container_name: multi-stage
    ports:
      - "3003:3000"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
